package com.zhifeng.dao;

import com.zhifeng.domain.User1;
import com.zhifeng.domain.User1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    long countByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int deleteByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int insert(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int insertSelective(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    User1 selectOneByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    User1 selectOneByExampleSelective(@Param("example") User1Example example, @Param("selective") User1.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    List<User1> selectByExampleSelective(@Param("example") User1Example example, @Param("selective") User1.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    List<User1> selectByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    User1 selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") User1.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    User1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") User1 record, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") User1 record, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User1 record);

    int insertUser(User1 user);
    int deleUser(int id);
    List<User1> Listuser();
    int updateUser(User1 user);
}